# GET http://localhost:4004/odata/v4/pan-approval/approve
# Content-Type: application/json

# {
#   "data": "Doc1025528402"
# }

GET http://localhost:4004/odata/v4/pan-approval/wf_data
Content-Type: application/json

{
  "panno": "Doc1025528402",
  "comment" : "demo comment"
}