# GET http://localhost:4004/odata/v4/pan-approval/approve
# Content-Type: application/json

# {
#   "data": "Doc1025528402"
# }

GET http://localhost:4004/odata/v4/pan-approval/approve
Content-Type: application/json

{
  "data": "Doc78427498",
  "email" : "rajendraakshay1@gmail.com"
}